#ifndef ICONS_H
#define ICONS_H

//#include "binary_icons/icon_01d.h"
//#include "binary_icons/icon_02d.h"
//#include "binary_icons/icon_03d.h"
//#include "binary_icons/icon_04d.h"
//#include "binary_icons/icon_09d.h"
//#include "binary_icons/icon_10d.h"
//#include "binary_icons/icon_11d.h"
//#include "binary_icons/icon_13d.h"
//#include "binary_icons/icon_50d.h"
//
//#include "binary_icons/icon_01n.h"
//#include "binary_icons/icon_02n.h"
//#include "binary_icons/icon_03n.h"
//#include "binary_icons/icon_04n.h"
//#include "binary_icons/icon_09n.h"
//#include "binary_icons/icon_10n.h"
//#include "binary_icons/icon_11n.h"
//#include "binary_icons/icon_13n.h"
//#include "binary_icons/icon_50n.h"
//
//#include "binary_icons/icon_s_01d.h"
//#include "binary_icons/icon_s_02d.h"
//#include "binary_icons/icon_s_03d.h"
//#include "binary_icons/icon_s_04d.h"
//#include "binary_icons/icon_s_09d.h"
//#include "binary_icons/icon_s_10d.h"
//#include "binary_icons/icon_s_11d.h"
//#include "binary_icons/icon_s_13d.h"
//#include "binary_icons/icon_s_50d.h"
//
//#include "binary_icons/icon_s_01n.h"
//#include "binary_icons/icon_s_02n.h"
//#include "binary_icons/icon_s_03n.h"
//#include "binary_icons/icon_s_04n.h"
//#include "binary_icons/icon_s_09n.h"
//#include "binary_icons/icon_s_10n.h"
//#include "binary_icons/icon_s_11n.h"
//#include "binary_icons/icon_s_13n.h"
//#include "binary_icons/icon_s_50n.h"

#include "binary_icons/icon_clear_night_100px.h"
#include "binary_icons/icon_cloudy_100px.h"
#include "binary_icons/icon_fog_100px.h"
#include "binary_icons/icon_hail_100px.h"
#include "binary_icons/icon_lightning_rainy_100px.h"
#include "binary_icons/icon_lightning_100px.h"
#include "binary_icons/icon_partlycloudy_100px.h"
#include "binary_icons/icon_pouring_100px.h"
#include "binary_icons/icon_rainy_100px.h"
#include "binary_icons/icon_snowy_rainy_100px.h"
#include "binary_icons/icon_snowy_100px.h"
#include "binary_icons/icon_sunny_100px.h"
#include "binary_icons/icon_windy_variant_100px.h"
#include "binary_icons/icon_windy_100px.h"
#include "binary_icons/icon_exceptional_100px.h"


#include "binary_icons/icon_clear_night_200px.h"
#include "binary_icons/icon_cloudy_200px.h"
#include "binary_icons/icon_fog_200px.h"
#include "binary_icons/icon_hail_200px.h"
#include "binary_icons/icon_lightning_rainy_200px.h"
#include "binary_icons/icon_lightning_200px.h"
#include "binary_icons/icon_partlycloudy_200px.h"
#include "binary_icons/icon_pouring_200px.h"
#include "binary_icons/icon_rainy_200px.h"
#include "binary_icons/icon_snowy_rainy_200px.h"
#include "binary_icons/icon_snowy_200px.h"
#include "binary_icons/icon_sunny_200px.h"
#include "binary_icons/icon_windy_variant_200px.h"
#include "binary_icons/icon_windy_200px.h"
#include "binary_icons/icon_exceptional_200px.h"

#include "binary_icons/icon_Sunrise_50px.h"
#include "binary_icons/icon_Sunset_50px.h"
#include "binary_icons/icon_Wind.h"

#endif
